version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: larvel-app
    container_name: laravel-app
    restart: unless-stopped
    environment:
      APP_DEBUG: true
      SESSION_DRIVER: file
      REDIS_HOST: redis
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: larvel-nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
